### ISSUE TITLE
Allow configuring a base path for the configuration UI

### ISSUE THREAD

**Issue by Henning-Schulz** [inspectIT/inspectit-ocelot#1239] opened 2021-11-24 15:30 UTC
I would like to specify a base path under which the configuration UI is reachable. For instance, several pages of the UI can be accessed via the following URLs:
* `host:port/ui`
* `host:port/ui/login`
* `host:port/ui/configuration`
* etc.

I would like to configure a base path, e.g., `my-config-server` such that the pages can be accessed via:
* `host:port/my-config-server/ui`
* `host:port/my-config-server/ui/login`
* `host:port/my-config-server/ui/configuration`
* etc.

**Comment by mariusoe** [comment] 2021-11-29 09:26
Duplicate of #601

**Closed by mariusoe** 2021-11-29 09:26 UTC
Labels: area/config-ui
