### ISSUE TITLE
Enable uploading files and folders in the configuration UI

### ISSUE THREAD

**Issue by Henning-Schulz** [inspectIT/inspectit-ocelot#1203] opened 2021-08-31 14:59 UTC
Given I have multiple configuration files, potentially structured in folders, that I all want to upload to the configuration server, I either have to manually place them in the working directory or create each file and folder separately in the UI. Both are cumbersome. Instead, it would be great to have an option in the UI to upload one or multiple files and folders.

**Comment by heiko-holz** [comment] 2022-06-07 08:13
Duplicate of #521

**Closed** 2022-06-07 08:14 UTC
Labels: duplicate, good first issue, area/config-ui
