### ISSUE TITLE
[Feature] - The service-name property of tracing exporter settings should be configurable during runtime

### ISSUE THREAD

**Issue by heiko-holz** [inspectIT/inspectit-ocelot#1450] opened 2022-05-25 13:30 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the `service-name` property of the `inspectit.exporters.tracing` settings only take effect when starting the agent. When the property is changed during runtime, it only takes effect after the agent has been restarted.

**Describe the solution you'd like**
Changes of the `service-name` property should take effect during runtime.

**Comment by MariusBrill** [comment] 2022-06-07 08:14
Duplicate of #1442

**Closed by MariusBrill** 2022-06-07 08:14 UTC
Labels: duplicate, idea
